#!/bin/bash

# args=$(git rev-parse --short "$@")

eval "git diff-tree -r $@" | {
  total=0
  while read A B C D M P; do
    if [[ -z $M ]]; then continue; fi
    case $M in
      M) bytes=$(( $(git cat-file -s $D || echo 0) - $(git cat-file -s $C || echo 0) )) ;;
      A) bytes=$(git cat-file -s $D) ;;
      D) bytes=-$(git cat-file -s $C) ;;
      *)
        echo >&2 warning: unhandled mode $M in \"$A $B $C $D $M $P\"
        continue
        ;;
    esac
    kbytes=$(( $bytes ))
    total=$(( $total + $bytes ))
    printf '%d\t%s\n' $bytes "$P"
  done
  if (( $total < 1000 )); then
    echo ${total} bytes
  else
    echo $(( total / 1000 ))KB
  fi
}