#!/bin/sh
#. git-sh-setup
args=$(git rev-parse "$@")
eval "git diff-tree -r $args" | {
  total=0
  while read A B C D M P
  do
    if [[ -z $M ]]; then continue; fi
    case $M in
      M) bytes=$(( $(git cat-file -s $D) - $(git cat-file -s $C) )) ;;
      A) bytes=$(git cat-file -s $D) ;;
      D) bytes=-$(git cat-file -s $C) ;;
      *)
        echo >&2 warning: unhandled mode $M in \"$A $B $C $D $M $P\"
        continue
        ;;
    esac
    total=$(( $total + $bytes ))
    printf '%d\t%s\n' $bytes "$P"
  done
  echo total $total
}