#!/bin/bash
set -e

# read -p "This will remove all dangling commits. Are you sure you want to proceed? [y/N] " yn
# case $yn in
#   [Yy]*) ;;
#   *) exit;;
# esac 

git gc --prune='8 weeks ago'
git repack --window=50 --depth=100 -f